// Generated by CoffeeScript 1.6.3
var packets;

packets = module.exports = {};

packets.toString = function(o) {
  return JSON.stringify(o);
};

packets.toObject = function(o) {
  var err;
  try {
    o = JSON.parse(o);
    return o;
  } catch (_error) {
    err = _error;
    return console.log("json parse error: " + o + " ");
  }
};

packets.emit = function(socket, cmd, data) {
  return socket.emit(cmd, this.toString(data));
};
