// Generated by CoffeeScript 1.6.3
var EventEmitter, merge, socket;

EventEmitter = require('events').EventEmitter;

merge = function(a, b) {
  var key;
  if (a && b) {
    for (key in b) {
      a[key] = b[key];
    }
  }
  return a;
};

socket = merge({}, EventEmitter.prototype);

socket.on('connect', function() {
  return console.log('connected!');
});

console.log(socket);

socket.emit('connect');
